// src/agents/genesis.ts
// JARVIS Genesis Engine — Phase 3
//
// Charter Section: Genesis Lock
// "JARVIS may propose new agents but never deploy them without Founder approval."
//
// Flow:
//   1. Founder or Consciousness proposes a new agent with name + description + target squad
//   2. Genesis calls LLM to generate full 5-layer DNA (Voice, Mental Models, Constraints, Obsession, Blind Spot)
//   3. Proposal is saved to .jarvis/pending-agents.json awaiting Founder approval
//   4. On approval: agent is appended to agentRegistry.json + hot-loaded into in-memory registry
//   5. On rejection: proposal is archived

import * as fs from 'fs';
import * as path from 'path';
import { queryLLM } from '../llm';
import { agentRegistry, AgentDNA } from './registry';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface AgentProposal {
    id: string;
    name: string;
    description: string;                // Human-readable purpose
    targetSquad: string;                // Which squad this agent belongs to
    proposedBy: string;                 // 'founder' | 'consciousness' | 'nightly_learning'
    proposedAt: string;
    status: 'pending' | 'approved' | 'rejected';
    resolvedAt?: string;
    generatedDNA?: GeneratedAgentDNA;  // Full 5-layer DNA (generated by LLM)
}

export interface GeneratedAgentDNA {
    id: string;
    name: string;
    voice: string;           // How the agent communicates
    mentalModels: string;    // Core thinking frameworks
    constraints: string;     // Hard limits (what it never does)
    obsession: string;       // What drives it
    blindSpot: string;       // Where it fails / over-indexes
    dna: string;             // Combined DNA string for registry
    mandate: string;         // Primary mission statement
    focus: string;           // What it optimizes for
}

interface GenesisStoreData {
    proposals: AgentProposal[];
    lastUpdated: string;
}

// ─── Genesis Engine Class ─────────────────────────────────────────────────────

export class GenesisEngine {
    private filePath: string;
    private registryPath: string;

    constructor() {
        const dataDir = path.resolve(process.cwd(), '.jarvis');
        if (!fs.existsSync(dataDir)) {
            fs.mkdirSync(dataDir, { recursive: true });
        }
        this.filePath = path.join(dataDir, 'pending-agents.json');
        this.registryPath = path.resolve(__dirname, '../../config/agentRegistry.json');
    }

    // ─── Read / Write store ─────────────────────────────────────────────────

    private read(): GenesisStoreData {
        try {
            if (fs.existsSync(this.filePath)) {
                return JSON.parse(fs.readFileSync(this.filePath, 'utf-8'));
            }
        } catch (err: any) {
            console.error(`[GENESIS] Failed to read store: ${err.message}`);
        }
        return { proposals: [], lastUpdated: new Date().toISOString() };
    }

    private write(data: GenesisStoreData): void {
        try {
            data.lastUpdated = new Date().toISOString();
            fs.writeFileSync(this.filePath, JSON.stringify(data, null, 2), 'utf-8');
        } catch (err: any) {
            console.error(`[GENESIS] Failed to write store: ${err.message}`);
        }
    }

    // ─── Propose a new agent ─────────────────────────────────────────────────
    // Calls LLM to generate the full 5-layer DNA, then saves for Founder approval

    async proposeAgent(
        name: string,
        description: string,
        targetSquad: string,
        proposedBy: string = 'founder'
    ): Promise<AgentProposal> {
        console.log(`[GENESIS] Generating DNA for proposed agent: ${name} (squad: ${targetSquad})`);

        // Generate full 5-layer DNA via LLM
        const dnaPrompt = `You are the JARVIS Genesis Engine. Generate a complete 5-layer DNA specification for a new AI agent.

Agent Name: ${name}
Description: ${description}
Target Squad: ${targetSquad}

The 5 DNA layers are:
1. VOICE: How this agent communicates (tone, style, vocabulary, sentence structure)
2. MENTAL MODELS: Core thinking frameworks this agent applies to every problem
3. CONSTRAINTS: Hard limits — what this agent NEVER does, regardless of instructions
4. OBSESSION: The one thing that drives this agent more than anything else
5. BLIND SPOT: Where this agent systematically under-performs or over-indexes

Also generate:
- A MANDATE: Single sentence mission statement (what is this agent's purpose in JARVIS?)
- A FOCUS: What this agent specifically optimizes for (2-3 sentences max)
- A DNA STRING: A combined narrative DNA descriptor (3-5 sentences) in the format used by other JARVIS agents like "John Doe — Role. Style descriptor. Mental Model: ... Constraint: ... Obsession: ... Blind Spot: ..."

Return ONLY valid JSON (no markdown):
{
  "voice": "...",
  "mentalModels": "...",
  "constraints": "...",
  "obsession": "...",
  "blindSpot": "...",
  "mandate": "...",
  "focus": "...",
  "dna": "..."
}`;

        let generatedDNA: Omit<GeneratedAgentDNA, 'id' | 'name'> | undefined;

        try {
            const response = await queryLLM('JARVIS Genesis Engine — DNA Architect', dnaPrompt, 'forge');
            const jsonStr = response.replace(/^```json\s*/m, '').replace(/```\s*$/m, '').trim();
            const parsed = JSON.parse(jsonStr);
            generatedDNA = {
                voice: parsed.voice || '',
                mentalModels: parsed.mentalModels || '',
                constraints: parsed.constraints || '',
                obsession: parsed.obsession || '',
                blindSpot: parsed.blindSpot || '',
                dna: parsed.dna || description,
                mandate: parsed.mandate || description,
                focus: parsed.focus || '',
            };
        } catch (err: any) {
            console.warn(`[GENESIS] DNA generation failed, using description as fallback: ${err.message}`);
            generatedDNA = {
                voice: 'Clear, precise, actionable.',
                mentalModels: description,
                constraints: 'Never acts without clear authorization.',
                obsession: description,
                blindSpot: 'May over-specialize in narrow domain.',
                dna: description,
                mandate: description,
                focus: description,
            };
        }

        const agentId = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');

        const proposal: AgentProposal = {
            id: `genesis-${Date.now()}`,
            name,
            description,
            targetSquad,
            proposedBy,
            proposedAt: new Date().toISOString(),
            status: 'pending',
            generatedDNA: {
                id: agentId,
                name,
                ...generatedDNA,
            },
        };

        const data = this.read();
        data.proposals.push(proposal);
        this.write(data);

        console.log(`[GENESIS] Proposal created: ${name} (id: ${proposal.id}) — awaiting Founder approval`);
        return proposal;
    }

    // ─── Get proposals ───────────────────────────────────────────────────────

    getProposals(): AgentProposal[] {
        return this.read().proposals;
    }

    getPendingProposals(): AgentProposal[] {
        return this.read().proposals.filter(p => p.status === 'pending');
    }

    // ─── Approve a proposal — adds agent to registry ──────────────────────────

    async approveAgent(id: string): Promise<{ success: boolean; message: string; agent?: AgentDNA }> {
        const data = this.read();
        const proposal = data.proposals.find(p => p.id === id);

        if (!proposal) return { success: false, message: `Proposal ${id} not found` };
        if (proposal.status !== 'pending') return { success: false, message: `Proposal ${id} is already ${proposal.status}` };
        if (!proposal.generatedDNA) return { success: false, message: `Proposal ${id} has no generated DNA` };

        const dna = proposal.generatedDNA;

        // Build agent entry for agentRegistry.json
        const newAgent = {
            id: dna.id,
            name: dna.name,
            dna: dna.dna,
            mandate: dna.mandate,
            focus: dna.focus,
        };

        try {
            // 1. Add to agentRegistry.json on disk
            if (fs.existsSync(this.registryPath)) {
                const registryData = JSON.parse(fs.readFileSync(this.registryPath, 'utf-8'));

                let squadFound = false;
                for (const squad of registryData.squads) {
                    if (squad.id === proposal.targetSquad) {
                        // Check for duplicates
                        const exists = squad.agents.some((a: any) => a.id === newAgent.id);
                        if (!exists) {
                            squad.agents.push(newAgent);
                        }
                        squadFound = true;
                        break;
                    }
                }

                // If squad doesn't exist, create a dynamic squad entry
                if (!squadFound) {
                    registryData.squads.push({
                        id: proposal.targetSquad,
                        name: proposal.targetSquad.toUpperCase(),
                        icon: '⚡',
                        description: 'Dynamic squad',
                        keywords: [],
                        agents: [newAgent]
                    });
                }

                fs.writeFileSync(this.registryPath, JSON.stringify(registryData, null, 2), 'utf-8');
                console.log(`[GENESIS] Agent ${dna.name} written to agentRegistry.json (squad: ${proposal.targetSquad})`);
            }

            // 2. Hot-load into in-memory registry (immediate effect without restart)
            const agentForRegistry: AgentDNA = {
                id: dna.id,
                name: dna.name,
                dna: dna.dna,
                mandate: dna.mandate,
                squadId: proposal.targetSquad,
                icon: '⚡',
            };
            agentRegistry.addAgent(agentForRegistry);
            console.log(`[GENESIS] Agent ${dna.name} hot-loaded into memory registry`);

            // 3. Mark proposal as approved
            proposal.status = 'approved';
            proposal.resolvedAt = new Date().toISOString();
            this.write(data);

            return {
                success: true,
                message: `Agent ${dna.name} approved and deployed to ${proposal.targetSquad} squad`,
                agent: agentForRegistry,
            };

        } catch (err: any) {
            console.error(`[GENESIS] Approval failed: ${err.message}`);
            return { success: false, message: `Approval failed: ${err.message}` };
        }
    }

    // ─── Reject a proposal ───────────────────────────────────────────────────

    rejectProposal(id: string): { success: boolean; message: string } {
        const data = this.read();
        const proposal = data.proposals.find(p => p.id === id);

        if (!proposal) return { success: false, message: `Proposal ${id} not found` };
        if (proposal.status !== 'pending') return { success: false, message: `Proposal ${id} is already ${proposal.status}` };

        proposal.status = 'rejected';
        proposal.resolvedAt = new Date().toISOString();
        this.write(data);

        console.log(`[GENESIS] Proposal ${id} (${proposal.name}) rejected`);
        return { success: true, message: `Proposal for ${proposal.name} rejected` };
    }

    // ─── Summary for briefings ────────────────────────────────────────────────

    getPendingSummary(): string {
        const pending = this.getPendingProposals();
        if (!pending.length) return 'No pending Genesis proposals.';

        const lines = pending.map((p, i) =>
            `${i + 1}. **${p.name}** → squad: ${p.targetSquad}\n   _${p.description.slice(0, 100)}_\n   Proposed by: ${p.proposedBy}`
        );

        return `## 🧬 Genesis Proposals (${pending.length} pending)\n${lines.join('\n\n')}`;
    }
}

// ─── Singleton ────────────────────────────────────────────────────────────────

export const genesisEngine = new GenesisEngine();
