// src/security/sandbox.ts
// JARVIS Sentinel Sandboxing Layer — Phase 3
//
// Charter: "Executes code generated by agents in a secure sandbox before
// running it in production. Prevents malicious or broken code from
// damaging the system."
//
// Architecture:
//   - JavaScript/TypeScript: Node.js vm module (isolated context, no require)
//   - Static Analysis: Pattern-based dangerous code detector
//   - Output: SandboxResult { safe, output, warnings, durationMs }
//
// Usage:
//   import { sandboxExecute, validateCodeSafety } from './sandbox';
//   const result = sandboxExecute(codeBlock, 5000);
//   if (!result.safe) { /* SENTINEL VETO */ }

import vm from 'vm';
import * as path from 'path';
import * as fs from 'fs';
import { logger } from '../logger';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SandboxResult {
    safe: boolean;
    executed: boolean;
    output: string;
    warnings: string[];
    blockedPatterns: string[];
    durationMs: number;
    staticAnalysis: StaticAnalysisResult;
}

export interface StaticAnalysisResult {
    riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    detectedPatterns: DetectedPattern[];
    approved: boolean;
}

export interface DetectedPattern {
    pattern: string;
    severity: 'WARNING' | 'BLOCK';
    description: string;
    line?: number;
}

// ─── Dangerous Pattern Registry ──────────────────────────────────────────────

const CRITICAL_PATTERNS: Array<{ pattern: RegExp; description: string }> = [
    { pattern: /require\s*\(\s*['"]child_process['"]\s*\)/g, description: 'Shell command execution via child_process' },
    { pattern: /require\s*\(\s*['"]fs['"]\s*\)/g, description: 'Direct filesystem access via require(fs)' },
    { pattern: /process\.exit/g, description: 'Process termination' },
    { pattern: /process\.env/g, description: 'Environment variable access (potential credential leak)' },
    { pattern: /eval\s*\(/g, description: 'Dynamic code evaluation (eval)' },
    { pattern: /Function\s*\(/g, description: 'Dynamic function construction' },
    { pattern: /\.exec\s*\(/g, description: 'Command execution (.exec)' },
    { pattern: /\.spawn\s*\(/g, description: 'Process spawning (.spawn)' },
    { pattern: /import\s+.*from\s+['"]child_process['"]/g, description: 'child_process import' },
    { pattern: /import\s+.*from\s+['"]fs['"]/g, description: 'fs module import' },
    { pattern: /__dirname|__filename/g, description: 'Filesystem path exposure' },
    { pattern: /rm\s+-rf|rmdir|unlink|deleteFile/g, description: 'File deletion operations' },
    { pattern: /XMLHttpRequest|fetch\s*\(/g, description: 'Network request from sandbox' },
    { pattern: /WebSocket/g, description: 'WebSocket connection from sandbox' },
    { pattern: /Buffer\.from|atob|btoa/g, description: 'Binary/encoding operations (possible data exfiltration)' },
];

const WARNING_PATTERNS: Array<{ pattern: RegExp; description: string }> = [
    { pattern: /while\s*\(\s*true\s*\)/g, description: 'Infinite loop (while true)' },
    { pattern: /for\s*\(;\s*;\s*\)/g, description: 'Infinite loop (for ;;)' },
    { pattern: /setInterval|setTimeout/g, description: 'Timer functions (may block execution)' },
    { pattern: /new\s+Array\(\d{7,}\)/g, description: 'Very large array allocation (memory concern)' },
    { pattern: /console\.(log|warn|error|info)/g, description: 'Console output' },
    { pattern: /Math\.random\(\)/g, description: 'Non-deterministic behavior (random)' },
    { pattern: /Date\.(now|parse)/g, description: 'Time-dependent behavior' },
];

// ─── Static Code Analysis ─────────────────────────────────────────────────────

export function validateCodeSafety(code: string): StaticAnalysisResult {
    const detectedPatterns: DetectedPattern[] = [];
    const lines = code.split('\n');

    // Check critical patterns
    for (const { pattern, description } of CRITICAL_PATTERNS) {
        const matches = code.match(pattern);
        if (matches) {
            // Find line numbers
            lines.forEach((line, idx) => {
                if (pattern.test(line)) {
                    detectedPatterns.push({
                        pattern: matches[0],
                        severity: 'BLOCK',
                        description,
                        line: idx + 1,
                    });
                }
            });
        }
    }

    // Check warning patterns
    for (const { pattern, description } of WARNING_PATTERNS) {
        const matches = code.match(pattern);
        if (matches) {
            detectedPatterns.push({
                pattern: matches[0],
                severity: 'WARNING',
                description,
            });
        }
    }

    const blockers = detectedPatterns.filter(p => p.severity === 'BLOCK');
    const warnings = detectedPatterns.filter(p => p.severity === 'WARNING');

    let riskLevel: StaticAnalysisResult['riskLevel'] = 'LOW';
    if (blockers.length >= 3) riskLevel = 'CRITICAL';
    else if (blockers.length >= 1) riskLevel = 'HIGH';
    else if (warnings.length >= 3) riskLevel = 'MEDIUM';

    return {
        riskLevel,
        detectedPatterns,
        approved: blockers.length === 0,
    };
}

// ─── Sandbox Execution (JavaScript only) ─────────────────────────────────────

export function sandboxExecute(
    code: string,
    timeoutMs: number = 5000
): SandboxResult {
    const start = Date.now();
    const output: string[] = [];
    const warnings: string[] = [];
    const blockedPatterns: string[] = [];

    // Step 1: Static analysis
    const staticAnalysis = validateCodeSafety(code);

    if (!staticAnalysis.approved) {
        const blockers = staticAnalysis.detectedPatterns
            .filter(p => p.severity === 'BLOCK')
            .map(p => `Line ${p.line || '?'}: ${p.description}`);

        logSandboxEvent('BLOCKED', code.slice(0, 100), blockers);

        return {
            safe: false,
            executed: false,
            output: '',
            warnings: [],
            blockedPatterns: blockers,
            durationMs: Date.now() - start,
            staticAnalysis,
        };
    }

    if (staticAnalysis.riskLevel === 'MEDIUM') {
        warnings.push(...staticAnalysis.detectedPatterns
            .filter(p => p.severity === 'WARNING')
            .map(p => p.description)
        );
    }

    // Step 2: Execute in isolated vm context
    try {
        const sandbox = {
            // Safe console capture
            console: {
                log: (...args: any[]) => output.push(args.map(String).join(' ')),
                warn: (...args: any[]) => { output.push('[WARN] ' + args.map(String).join(' ')); },
                error: (...args: any[]) => { output.push('[ERROR] ' + args.map(String).join(' ')); },
                info: (...args: any[]) => output.push('[INFO] ' + args.map(String).join(' ')),
            },
            // Safe Math & JSON
            Math,
            JSON,
            parseInt,
            parseFloat,
            isNaN,
            isFinite,
            String,
            Number,
            Boolean,
            Array,
            Object,
            // No process, require, fetch, etc.
        };

        const context = vm.createContext(sandbox);
        vm.runInContext(code, context, {
            timeout: timeoutMs,
            filename: 'sandbox.js',
            displayErrors: true,
        });

        logSandboxEvent('EXECUTED', code.slice(0, 100), []);

        return {
            safe: true,
            executed: true,
            output: output.join('\n'),
            warnings,
            blockedPatterns: [],
            durationMs: Date.now() - start,
            staticAnalysis,
        };

    } catch (err: any) {
        const errMsg = err.message || String(err);
        const isTimeout = errMsg.includes('Script execution timed out');

        logSandboxEvent('RUNTIME_ERROR', code.slice(0, 100), [errMsg]);

        return {
            safe: !isTimeout, // Timeout is a security concern
            executed: false,
            output: '',
            warnings: [errMsg],
            blockedPatterns: isTimeout ? ['Execution timeout — possible infinite loop'] : [],
            durationMs: Date.now() - start,
            staticAnalysis,
        };
    }
}

// ─── Extract code blocks from agent output ────────────────────────────────────

export function extractCodeBlocks(text: string): Array<{ lang: string; code: string }> {
    const blocks: Array<{ lang: string; code: string }> = [];
    const regex = /```(\w+)?\n([\s\S]*?)```/g;
    let match;

    while ((match = regex.exec(text)) !== null) {
        blocks.push({
            lang: match[1] || 'text',
            code: match[2].trim(),
        });
    }

    return blocks;
}

// ─── Validate all code blocks in a Forge squad response ──────────────────────
// Returns a SENTINEL VETO if any code block is dangerous

export interface ForgeValidationResult {
    approved: boolean;
    vetoed: boolean;
    vetoReason?: string;
    blocksAnalyzed: number;
    warnings: string[];
}

export function validateForgeOutput(agentOutput: string): ForgeValidationResult {
    const codeBlocks = extractCodeBlocks(agentOutput);

    if (!codeBlocks.length) {
        return { approved: true, vetoed: false, blocksAnalyzed: 0, warnings: [] };
    }

    const allWarnings: string[] = [];

    for (const block of codeBlocks) {
        // Only sandbox JS/TS blocks
        if (!['js', 'javascript', 'ts', 'typescript'].includes(block.lang.toLowerCase())) {
            continue;
        }

        const analysis = validateCodeSafety(block.code);

        if (!analysis.approved) {
            const blockers = analysis.detectedPatterns
                .filter(p => p.severity === 'BLOCK')
                .map(p => p.description);

            return {
                approved: false,
                vetoed: true,
                vetoReason: `🛡️ SENTINEL VETO\n**Risk:** Dangerous code pattern detected in Forge output\n**Agent:** SENTINEL Sandboxing Layer\n**Level:** HIGH\n**Patterns:** ${blockers.join('; ')}\n**Mitigação requerida:** Review and remove dangerous patterns before execution\n**Decisão do Fundador requerida:** SIM`,
                blocksAnalyzed: codeBlocks.length,
                warnings: blockers,
            };
        }

        if (analysis.riskLevel === 'MEDIUM') {
            allWarnings.push(...analysis.detectedPatterns
                .filter(p => p.severity === 'WARNING')
                .map(p => p.description)
            );
        }
    }

    return {
        approved: true,
        vetoed: false,
        blocksAnalyzed: codeBlocks.length,
        warnings: allWarnings,
    };
}

// ─── Logging ─────────────────────────────────────────────────────────────────

function logSandboxEvent(event: string, codeSnippet: string, details: string[]): void {
    const logDir = path.resolve(process.cwd(), 'logs');
    const logFile = path.join(logDir, 'sandbox.log');

    const entry = {
        timestamp: new Date().toISOString(),
        event,
        codeSnippet: codeSnippet.replace(/\n/g, ' '),
        details,
    };

    try {
        if (!fs.existsSync(logDir)) fs.mkdirSync(logDir, { recursive: true });
        fs.appendFileSync(logFile, JSON.stringify(entry) + '\n');
    } catch { /* ignore logging failures */ }

    if (event === 'BLOCKED') {
        logger.warn(`[SANDBOX] ${event}: ${details.join('; ')}`);
    }
}
